name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --verbose

      - name: Run tests with coverage
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: latest
        # OR manually:
        # run: cargo install cargo-tarpaulin && cargo tarpaulin --out Lcov --output-dir ./coverage

      - name: Upload coverage to SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

